work_dir: ./work_dir/ntu60/xsub/ctrgcn_joint  # 保存的目录

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: autodl-tmp/competition/data/train_joint.npy #data/ntu/NTU60_CS.npz  # 生成的NTU60数据集的npz文件的绝对路径
  label_path: autodl-tmp/competition/data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: True
  random_move: True
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: True # 控制骨骼流和关节流的选项，False表示关节流joint,True表示骨骼流bone

test_feeder_args:
  data_path: autodl-tmp/competition/data/test_A_joint.npy #data/ntu/NTU60_CS.npz # 测试集npz文件的绝对路径
  label_path: autodl-tmp/competition/data/test_A_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: True
  bone: True
  debug: False

# model
model: model.ctrgcn.Model  # 选用的模型，model文件下的ctrgcn.py文件下的model类
model_args:
  num_class: 155 #60  #数据集有60个类别，25个关节结点，2个测试人
  num_point: 17  #25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [80, 90]
warm_up_epoch: 10

# training
device: [0]  # 显卡的序号，如果使用2张显卡，用,隔开，例如[0,1]
batch_size: 64 # 训练批次大小
test_batch_size: 64
num_epoch: 100  # 训练轮次
nesterov: True
