work_dir: ./work_dir/ntu120/xsub/ctrgcn_joint

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: autodl-tmp/competition/data/train_joint.npy #data/ntu/NTU60_CS.npz  # 生成的NTU60数据集的npz文件的绝对路径
  label_path: autodl-tmp/competition/data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: True
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: autodl-tmp/competition/data/test_A_joint.npy #data/ntu/NTU60_CS.npz # 测试集npz文件的绝对路径
  label_path: autodl-tmp/competition/data/test_A_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: model.degcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  k: 8
  eta: 4
  num_stream: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
step: [35,60,75]
warm_up_epoch: 5
cosine_epoch: 60

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 80
nesterov: True
